language: python
python:

  - "3.5"
  - "3.5-dev"  # 3.5 development branch
  - "3.6"

# command to install dependencies

# command to run tests
script:
  - pytest # or py.test for Python versions 3.5 and below